name: run-export
on:
  schedule:
  - cron:  '0 5,23 * * *'
jobs:
  buildx:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout the source code'
        uses: actions/checkout@v2
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v1
      - name: 'Set up Docker Buildx cache'
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: 'Build container image'
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            --platform "linux/amd64" \
            -o .reports \
            --build-arg PROJECT_ID=${{ secrets.PROJECT_ID }} \
            --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} \
            --build-arg CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }} \
            --build-arg PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
            --build-arg DATASET_NAME=${{ secrets.DATASET_NAME }} \
            --build-arg RUN_ID=${{ github.run_id }} \
            --target "jobs-done" \
            --file "./Dockerfile" \
            "./"
